config/routes.rb
Blog::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users

  root to: 'posts#index', via: :get

  resources :posts, only: [:show, :index] do
    resources :comments, only: [:create, :destroy]
  end

  get 'categories/:category', to: 'posts#index', as: :category
  get 'author/:author',       to: 'posts#index', as: :user
  get 'tags/:tag',            to: 'posts#index', as: :tag

  authenticate :user do
    namespace :admin do
      root to: 'dashboard#show'
      resources :users do
        post :recover, on: :member
      end
      resources :posts, except: :show
      resources :categories, except: :show
    end
  end

end

app/helpers/navigation_helper.rb
module NavigationHelper
  def path_active(path)
    yield path, path_active?(path)
  end

  def path_active?(path)
    @breadcrumbs.any? do |breadcrumb|
      breadcrumb_path = breadcrumb.path
      breadcrumb_path =  send(breadcrumb_path) if breadcrumb_path.is_a? Symbol
      breadcrumb_path == path
    end
  end

  def path_active_class(path)
    path ? :active : nil
  end

  def paginate(colleciton)
    will_paginate colleciton, renderer: BootstrapPagination::Rails
  end
end

app/views/shared/navigation/_auth.html.haml
%li=link_to icon(:gears, 'administration'), admin_root_path if can? :show, Admin
-if user_signed_in?
  %li=link_to icon(:'sign-out', 'sign out'), destroy_user_session_path, method: :delete
-else
  %li=link_to icon(:'sign-in', 'sign in'), new_user_session_path