config/routes.rb
Blog::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users

  root to: 'posts#index', via: :get

  resources :posts, only: [:show, :index] do
    resources :comments, only: [:create, :destroy]
  end

  get 'categories/:category', to: 'posts#index', as: :category
  get 'author/:author',       to: 'posts#index', as: :user
  get 'tags/:tag',            to: 'posts#index', as: :tag

  authenticate :user do
    namespace :admin do
      root to: 'dashboard#show'
      resources :users do
        post :recover, on: :member
      end
      resources :posts, except: :show
      resources :categories, except: :show
    end
  end

end

app/models/post.rb
class Post
  include Mongoid::Document
  # include Mongoid::Versioning
  include Mongoid::Timestamps
  include Mongoid::Document::Taggable

  belongs_to :author, class_name: 'User'
  belongs_to :category
  embeds_many :comments

  field :_id,   type: String, default: -> { "#{title}".parameterize }
  field :title, type: String
  field :lead,  type: String
  field :body,  type: String

  field :published_at, type: Time

  validates :title, :body, :category_id, presence: true
  scope :published, -> { where(:published_at.exists => true).and(:published_at.lte => Date.today) }
  scope :ordered,   -> { order_by :published_at.desc }

  def tags=(value)
    value = value.split(',').map(&:strip) if value.is_a?(String)
    self[:tags] = value
  end

  def humanize
    "#{title}"
  end

  def operations(group = nil)
    Post::Operations.new self, group
  end

  def published?
    published_at.present? && published_at <= Time.now
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    load_and_authorize_resource :post
    add_breadcrumb 'posts', :admin_posts_path
    before_filter :add_post_breadcrumb, except: :index

    def index
      @posts = @posts.ordered.page(params[:page])
      respond_with @posts
    end

    def new
      respond_with @post
    end

    def create
      @post.update_attributes(params[:post].merge(author: current_user))
      if @post.valid?
        respond_with @post, location: request.referer
      else
        render :new
      end
    end

    def edit
      respond_with @post
    end

    def update
      @post.update_attributes(params[:post])
      if @post.valid?
        respond_with @post, location: request.referer
      else
        render :edit
      end
    end

    def destroy
      @post.destroy
      respond_with @user, location: request.referer
    end

    private

    def add_post_breadcrumb
      if @post.present?
        if @post.persisted?
          add_breadcrumb @post.humanize
        else
          add_breadcrumb 'new post'
        end
      end
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource :post
  before_filter :add_post_breadcrumb,       except: :index
  before_filter :ensure_post_is_published!, except: :index
  before_filter :apply_user_filter,         only: :index
  before_filter :apply_category_filter,     only: :index
  before_filter :apply_tag_filter,          only: :index

  def index
    @posts = @posts.published.ordered.paginate(page: params[:page], per_page: 5)
    respond_with @posts
  end

  def show
    @comment = Comment.new
    respond_with @post
  end

  def comment
    @comment = @post.comments.create(params[:comment])
    if @comment.valid?
      flash[:success] = 'Post has been commented.'
      respond_with @comment, location: post_path
    else
      flash[:warning] = 'An error occured.'
      render :show
    end
  end

  private

  # filter by :author param
  def apply_user_filter
    return if params[:author].blank?
    User.find(params[:author]).tap do |user|
      @posts = @posts.where author: user
      add_breadcrumb "by author \"#{user.humanize}\""
    end
  end

  # filter by category param
  def apply_category_filter
    return if params[:category].blank?
    Category.find(params[:category]).tap do |category|
      @posts = @posts.where category: category
      add_breadcrumb "by category \"#{category.humanize}\""
    end
  end

  # filter by :tag param
  def apply_tag_filter
    return if params[:tag].blank?
    params[:tag].tap do |tag|
      @posts = @posts.tagged_with tag
      add_breadcrumb "by tag \"#{tag}\""
    end
  end


  def ensure_post_is_published!
    raise ActiveRecord::RecordNotFound unless @post.published?
  end

  def add_post_breadcrumb
    if @post.present?
      if @post.persisted?
        add_breadcrumb @post.humanize
      else
        add_breadcrumb 'new post'
      end
    end
  end
end

app/views/posts/_new_comment.html.haml
%h3 Add comment!
=simple_form_for(@comment, url: post_comments_path(post_id: @post.id)) do |f|
  =f.input :body, as: :text
  =f.input :author
  =f.submit class: %i(btn btn-default)

app/views/posts/_post.html.haml
%article
  %h2=link_to post.title, post
  %div=simple_format post.lead
  %div=link_to 'read more', post
  %dl
    %dt Author
    %dd=link_to post.author.humanize, post.author
    %dt Category
    %dd=link_to post.category.humanize, post.category
    %dt Publication date
    %dd=time_tag post.published_at

app/views/posts/_tag.html.haml
=link_to tag, tag_path(tag), class: :badge

app/views/posts/index.html.haml
=render partial: @posts, as: :post
=paginate @posts

app/views/posts/show.html.haml
%article
  %h1.page-header=@post.title
  %div=simple_format @post.lead

  %dl
    %dt Author
    %dd=link_to @post.author.humanize, @post.author
    %dt Category
    %dd=link_to @post.category.humanize, @post.category
    %dt Publication date
    %dd=time_tag @post.published_at

  .article-body=@post.body.html_safe
  - if @post.tags.any?
    .tags
      Słowa kluczowe:
      = render collection: @post.tags, partial: 'tag', as: :tag
  %hr/
  = render 'new_comment' if can? :comment, @post
  %hr/
  .article-comments
    = render partial: @post.comments.ordered, as: :comment